/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Util.Utilidades;
import com.mycompany.coches.modelo.Cliente;
import com.mycompany.coches.modelo.Coche;
import com.mycompany.coches.modelo.Concesionario;
import com.mycompany.coches.modelo.Fabricante;
import com.mycompany.coches.modelo.Venta;
import java.awt.Event;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antonio Martínez Díaz
 */
public class FormularioVenta extends javax.swing.JPanel implements MouseListener{

    /**
     * Creates new form FormularioVenta2
     */
    private Coche coche;
    private Cliente cliente;
    private Concesionario concesionario;
    private DefaultTableModel modeloCliente;
    private DefaultTableModel modeloConcesionario;
    private DefaultTableModel modeloCoche;
    
    private int idCoche;
    private int idConcesionario;
    private int idCliente;
    
    
    
    
    public FormularioVenta() {
        initComponents();
        modeloCoche  = (DefaultTableModel)tablaCoche.getModel();
        modeloConcesionario = (DefaultTableModel)tablaConcesionario.getModel();
        modeloCliente = (DefaultTableModel)tablaCliente.getModel();
        this.tablaCliente.addMouseListener(this);
        this.tablaConcesionario.addMouseListener(this);
        this.tablaCoche.addMouseListener(this);
        this.inicializarTablaCoches();
        this.inicializarTablaConcesionarios();
        this.inicializarTablaClientes();
        
        
    }
    
    
   private void inicializarTablaCoches() {
    List<Coche>coches = Controlador.devolverCoches();
          for (Coche coche : coches) {
            if(coche !=null){
               modeloCoche.addRow(new Object[]{coche.getId(),coche.getBastidor(),coche.getModelo(),coche.getColor()}); 
            }
        }       
    }
    
   private void inicializarTablaConcesionarios(){
    List<Concesionario>concesionarios = Controlador.devolverConcesionarios();
          for (Concesionario concesionario :concesionarios) {
            if(concesionario!=null){
               modeloConcesionario.addRow(new Object[]{concesionario.getId(),concesionario.getCif(),concesionario.getLocalidad(),concesionario.getNombre()}); 
            }
        }       
    }
    
   private void inicializarTablaClientes(){
    List<Cliente>clientes = Controlador.devolverClientes();
          for (Cliente cliente :clientes ) {
            if(cliente !=null && !cliente.getNombre().equals("desconocido")){
             modeloCliente.addRow(new Object[]{cliente.getId(),
                 cliente.getNombre(),cliente.getApellidos(),
                 cliente.getLocalidad(),cliente.getDniNie(),cliente.getFecha()}); 
            }
        }       
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fVenta = new javax.swing.JTextField();
        Bastidor = new javax.swing.JLabel();
        fPrecioVenta = new javax.swing.JTextField();
        Bastidor1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        fFechaCliente = new javax.swing.JTextField();
        Bastidor4 = new javax.swing.JLabel();
        fNombreCliente = new javax.swing.JTextField();
        Bastidor2 = new javax.swing.JLabel();
        Bastidor3 = new javax.swing.JLabel();
        fApellidosCliente = new javax.swing.JTextField();
        fLocalidadCliente = new javax.swing.JTextField();
        Bastidor5 = new javax.swing.JLabel();
        Bastidor6 = new javax.swing.JLabel();
        fDniCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaConcesionario = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        fCifConcesionario = new javax.swing.JTextField();
        fNombreConcesionaio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fLocalidadConcesionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCoche = new javax.swing.JTable();
        Modelo = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        fBastidorCoche = new javax.swing.JTextField();
        Color1 = new javax.swing.JLabel();
        Modelo1 = new javax.swing.JLabel();
        Bastidor7 = new javax.swing.JLabel();
        fNombreFabricante = new javax.swing.JTextField();
        fColorCoche = new javax.swing.JTextField();
        fModeloCoche = new javax.swing.JTextField();
        fCifFabricante = new javax.swing.JTextField();
        guardarVenta = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 900));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nueva venta:");

        Bastidor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bastidor.setText("Fecha venta");

        Bastidor1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bastidor1.setText("Precio venta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Seleciona un coche");

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellidos", "Localidad", "Dni", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaCliente);

        fFechaCliente.setEditable(false);
        fFechaCliente.setBackground(new java.awt.Color(204, 204, 204));

        Bastidor4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bastidor4.setText("Fecha Nacimiento");

        fNombreCliente.setEditable(false);
        fNombreCliente.setBackground(new java.awt.Color(204, 204, 204));

        Bastidor2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bastidor2.setText("Nombre");

        Bastidor3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bastidor3.setText("Apellidos");

        fApellidosCliente.setEditable(false);
        fApellidosCliente.setBackground(new java.awt.Color(204, 204, 204));

        fLocalidadCliente.setEditable(false);
        fLocalidadCliente.setBackground(new java.awt.Color(204, 204, 204));

        Bastidor5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bastidor5.setText("Localidad");

        Bastidor6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bastidor6.setText("Dni");

        fDniCliente.setEditable(false);
        fDniCliente.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Seleciona un cliente");

        tablaConcesionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cif", "Nombre", "Localidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaConcesionario);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cif");

        fCifConcesionario.setEditable(false);
        fCifConcesionario.setBackground(new java.awt.Color(204, 204, 204));
        fCifConcesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCifConcesionarioActionPerformed(evt);
            }
        });

        fNombreConcesionaio.setEditable(false);
        fNombreConcesionaio.setBackground(new java.awt.Color(204, 204, 204));
        fNombreConcesionaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNombreConcesionaioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nombre");

        fLocalidadConcesionario.setEditable(false);
        fLocalidadConcesionario.setBackground(new java.awt.Color(204, 204, 204));
        fLocalidadConcesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fLocalidadConcesionarioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Localidad");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Seleciona un concesionario");

        tablaCoche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Bastidor", "Modelo", "Color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaCoche);

        Modelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Modelo.setText("Modelo");

        Color.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Color.setText("Color");

        fBastidorCoche.setEditable(false);
        fBastidorCoche.setBackground(new java.awt.Color(204, 204, 204));

        Color1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Color1.setText("Casa fabricate");

        Modelo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Modelo1.setText("CifFabricate");

        Bastidor7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bastidor7.setText("Bastidor");

        fNombreFabricante.setEditable(false);
        fNombreFabricante.setBackground(new java.awt.Color(204, 204, 204));
        fNombreFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNombreFabricanteActionPerformed(evt);
            }
        });

        fColorCoche.setEditable(false);
        fColorCoche.setBackground(new java.awt.Color(204, 204, 204));
        fColorCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fColorCocheActionPerformed(evt);
            }
        });

        fModeloCoche.setEditable(false);
        fModeloCoche.setBackground(new java.awt.Color(204, 204, 204));
        fModeloCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fModeloCocheActionPerformed(evt);
            }
        });

        fCifFabricante.setEditable(false);
        fCifFabricante.setBackground(new java.awt.Color(204, 204, 204));
        fCifFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCifFabricanteActionPerformed(evt);
            }
        });

        guardarVenta.setText("Guardar");
        guardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bastidor7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(Color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fBastidorCoche, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                            .addComponent(fModeloCoche)
                            .addComponent(fColorCoche))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Bastidor2)
                                        .addComponent(Bastidor3)
                                        .addComponent(Bastidor5)
                                        .addComponent(Bastidor6)
                                        .addComponent(Bastidor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fNombreCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fApellidosCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fLocalidadCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fDniCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fFechaCliente, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Bastidor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(fVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Bastidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(fPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGap(51, 51, 51)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fLocalidadConcesionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                                        .addComponent(fNombreConcesionaio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fCifConcesionario, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Modelo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Color1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fCifFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fNombreFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarVenta)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bastidor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bastidor1))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bastidor2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bastidor3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fLocalidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bastidor5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bastidor6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fFechaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bastidor4))
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fCifConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNombreConcesionaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fLocalidadConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fBastidorCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bastidor7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fModeloCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modelo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Color)
                    .addComponent(fColorCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fCifFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modelo1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNombreFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Color1))
                .addGap(59, 59, 59)
                .addComponent(guardarVenta)
                .addContainerGap(798, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fCifConcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCifConcesionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCifConcesionarioActionPerformed

    private void fNombreConcesionaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNombreConcesionaioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNombreConcesionaioActionPerformed

    private void fLocalidadConcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fLocalidadConcesionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fLocalidadConcesionarioActionPerformed

    private void fNombreFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNombreFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNombreFabricanteActionPerformed

    private void fColorCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fColorCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fColorCocheActionPerformed

    private void fModeloCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fModeloCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fModeloCocheActionPerformed

    private void fCifFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCifFabricanteActionPerformed

    }//GEN-LAST:event_fCifFabricanteActionPerformed

    private void guardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarVentaActionPerformed
           Venta venta = new Venta();           
           venta.setFecha(fVenta.getText());
           venta.setPrecio(Float.parseFloat(fPrecioVenta.getText()));
            
           if(this.coche !=null && this.cliente!=null && this.concesionario!=null){
              Controlador.crearVenta(venta, idCoche, idConcesionario, idCliente);
           
           
           
           }
           
           
           
         
           
           
           
           
           
            
            
            
            
        
        
        
        
        
    }//GEN-LAST:event_guardarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bastidor;
    private javax.swing.JLabel Bastidor1;
    private javax.swing.JLabel Bastidor2;
    private javax.swing.JLabel Bastidor3;
    private javax.swing.JLabel Bastidor4;
    private javax.swing.JLabel Bastidor5;
    private javax.swing.JLabel Bastidor6;
    private javax.swing.JLabel Bastidor7;
    private javax.swing.JLabel Color;
    private javax.swing.JLabel Color1;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel Modelo1;
    private javax.swing.JTextField fApellidosCliente;
    private javax.swing.JTextField fBastidorCoche;
    private javax.swing.JTextField fCifConcesionario;
    private javax.swing.JTextField fCifFabricante;
    private javax.swing.JTextField fColorCoche;
    private javax.swing.JTextField fDniCliente;
    private javax.swing.JTextField fFechaCliente;
    private javax.swing.JTextField fLocalidadCliente;
    private javax.swing.JTextField fLocalidadConcesionario;
    private javax.swing.JTextField fModeloCoche;
    private javax.swing.JTextField fNombreCliente;
    private javax.swing.JTextField fNombreConcesionaio;
    private javax.swing.JTextField fNombreFabricante;
    private javax.swing.JTextField fPrecioVenta;
    private javax.swing.JTextField fVenta;
    private javax.swing.JButton guardarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaCoche;
    private javax.swing.JTable tablaConcesionario;
    // End of variables declaration//GEN-END:variables

     private int idTabla(DefaultTableModel modelo,JTable tabla,MouseEvent e) {
       int fila = tabla.rowAtPoint(e.getPoint()); 
       int Id = (int) modelo.getValueAt(fila, 0);
       return Id;
    }

     
    
    private void clienteClicado(MouseEvent e){
    
      int id =  idTabla(modeloCliente,tablaCliente,e);
      
      if(id >0){
       this.idCliente = id;
       this.cliente =Controlador.obtenerCliente(id);
       if(cliente!=null){
           fNombreCliente.setText(cliente.getNombre());
           fApellidosCliente.setText(cliente.getApellidos());
           fLocalidadCliente.setText(cliente.getLocalidad());
           fDniCliente.setText(cliente.getDniNie());
           fFechaCliente.setText(cliente.getFecha());
       }
      }
    }
    
    private void concesionarioClicado(MouseEvent e){
       
      int id =  idTabla(modeloConcesionario,tablaConcesionario,e);
      if(id >0){
       this.idConcesionario = id;
       this.concesionario =Controlador.obtenerConcesioanrio(id);
       if(concesionario!=null){
         fCifConcesionario.setText(concesionario.getCif());
         fNombreConcesionaio.setText(concesionario.getNombre());
         fLocalidadConcesionario.setText(concesionario.getLocalidad());
       }
      }
    }
    
    private void cocheClicado(MouseEvent e){   
      int id =  idTabla(modeloCoche,tablaCoche,e);
      if(id >0){
      this.coche = coche = Controlador.obtenerCoche(id);
      this.idCoche = id;
       if(coche!=null){
         fBastidorCoche.setText(coche.getBastidor());
         fModeloCoche.setText(coche.getModelo());
         fColorCoche.setText(coche.getColor());
         Fabricante fabricante = coche.getFabricante();
         if(fabricante !=null){
             fCifFabricante.setText(fabricante.getCif());
             fNombreFabricante.setText(fabricante.getNombre());
         }
       }
      }
    }
    
    
    
    @Override
    public void mouseClicked(MouseEvent e) {
        
        if(e.getSource() == tablaCliente){
           clienteClicado(e);  
        }

        if(e.getSource() == tablaConcesionario){
            concesionarioClicado(e);
        }
       
        if(e.getSource() == tablaCoche){
            cocheClicado(e);
        }
        
        
  
    }

    @Override
    public void mousePressed(MouseEvent e) {
       
    }

    @Override
    public void mouseReleased(MouseEvent e) {
     
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
      
    }
}
