/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Util.Utilidades;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Controlador.Controlador;
import com.mycompany.coches.modelo.Fabricante;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author Antonio Martinez Diaz
 */
public class TablaVentas extends javax.swing.JFrame implements MouseListener, TableModelListener{

    private ModeloTabla modelo;
    private static ArrayList<String> titulosList;
   // private static String busqueda; 
    //private static int campoBusqueda;
    //private DefaultTableModel modeleloResultado;
    
    
    /**
     * Creates new form TablaVentas
     */
    public TablaVentas() {
        initComponents();
         construirTabla();
        tVentas.addMouseListener(this);
        tVentas.getModel().addTableModelListener(this);
       // busqueda = "";
       // campoBusqueda = Utilidades.NOMBRE;
       // modeleloResultado = (DefaultTableModel) tablaResultado.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tVentas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        crearCliente = new javax.swing.JMenuItem();
        crearFabricante = new javax.swing.JMenuItem();
        crearConsionario = new javax.swing.JMenuItem();
        crearCoche = new javax.swing.JMenuItem();
        crearVenta = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tVentas);

        jButton1.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ventas");

        jMenu2.setText("Gestionar");

        jMenu3.setText("Nuevo");

        crearCliente.setText("Cliente");
        crearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteActionPerformed(evt);
            }
        });
        jMenu3.add(crearCliente);

        crearFabricante.setText("Fabricante");
        crearFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearFabricanteActionPerformed(evt);
            }
        });
        jMenu3.add(crearFabricante);

        crearConsionario.setText("Concesionario");
        crearConsionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearConsionarioActionPerformed(evt);
            }
        });
        jMenu3.add(crearConsionario);

        crearCoche.setText("Coche");
        crearCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCocheActionPerformed(evt);
            }
        });
        jMenu3.add(crearCoche);

        crearVenta.setText("Venta");
        crearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVentaActionPerformed(evt);
            }
        });
        jMenu3.add(crearVenta);

        jMenu2.add(jMenu3);

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteActionPerformed
        JDialog a = emergenteA(0, "Nuevo Cliente");
        a.add(new FormularioCliente());
        emergeteB(a);        // TODO add your handling code here:
    }//GEN-LAST:event_crearClienteActionPerformed

    private void crearFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearFabricanteActionPerformed
         JDialog a = emergenteA(0, "Nuevo fabricate");
        a.add(new FormularioFabricante());
        emergeteB(a);        // TODO add your handling code here:
    }//GEN-LAST:event_crearFabricanteActionPerformed

    private void crearConsionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearConsionarioActionPerformed
        JDialog a = emergenteA(0, "Nuevo Concesionario");
        a.add(new FormularioConcesionario());
        emergeteB(a); 
    }//GEN-LAST:event_crearConsionarioActionPerformed

    private void crearCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCocheActionPerformed
        JDialog a = emergenteA(0, "Nuevo Coche");
        a.add(new FormularioNuevoCoche());
        emergeteB(a); 
    }//GEN-LAST:event_crearCocheActionPerformed

    private void crearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVentaActionPerformed
       JDialog a = emergenteA(0, "Nueva venta");
        a.add(new FormularioVenta());
        emergeteB(a); 
                
    }//GEN-LAST:event_crearVentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialog a = emergenteA(0, "Eliminar");
        a.add(new Eliminar());
        emergeteB(a);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    
      public void construirTabla() {
        titulosList = new ArrayList<>();
        titulosList.add("Id");
        titulosList.add("Fecha");
        titulosList.add("Precio");
        titulosList.add("");
        titulosList.add("");
        titulosList.add("");
        titulosList.add("");
  


        String titulos[] = new String[titulosList.size()];
        for (int i = 0; i < titulos.length; i++) {
            titulos[i] = titulosList.get(i);
        }

        Object[][] data = obtenerMatrizDatos(titulosList);
        construirTabla(titulos, data);
    }

      
      
     private Object[][] obtenerMatrizDatos(ArrayList<String> titulosList) {
        String informacion[][] = new String[Controlador.devolverVentas().size()][titulosList.size()];
        for (int x = 0; x < informacion.length; x++) {
            informacion[x][Utilidades.ID] = Controlador.obtenerCampoMo("id", x);
            informacion[x][Utilidades.FECHA] = Controlador.obtenerCampoMo("fecha", x);
            informacion[x][Utilidades.PRECIO] = Controlador.obtenerCampoMo("precio", x);
            informacion[x][Utilidades.COCHE] = "COCHE";
            informacion[x][Utilidades.CONCESIONARIO] = "CONCESIONARIO";
            informacion[x][Utilidades.CLIENTE] = "CLIENTE";
            informacion[x][Utilidades.ELIMINAR] = "ELIMINAR";
        }
        return informacion;
    }
      
      
    public void restaurarEscucha() {
        tVentas.getModel().removeTableModelListener(this);
        tVentas.getModel().addTableModelListener(this);
    }
    
    
      private void construirTabla(String[] titulos, Object[][] data) {
        modelo = new ModeloTabla(data, titulos);
        tVentas.setModel(modelo);
        tVentas.getColumnModel().getColumn(Utilidades.COCHE).setPreferredWidth(100);
        tVentas.getColumnModel().getColumn(Utilidades.CLIENTE).setPreferredWidth(100);
        tVentas.getColumnModel().getColumn(Utilidades.CONCESIONARIO).setPreferredWidth(130);
        tVentas.getColumnModel().getColumn(Utilidades.ELIMINAR).setPreferredWidth(130);
        tVentas.getColumnModel().getColumn(Utilidades.COCHE).setCellRenderer(new GestionCeldas("icono")); 
        tVentas.getColumnModel().getColumn(Utilidades.CLIENTE).setCellRenderer(new GestionCeldas("icono")); 
        tVentas.getColumnModel().getColumn(Utilidades.CONCESIONARIO).setCellRenderer(new GestionCeldas("icono")); 
        tVentas.getColumnModel().getColumn(Utilidades.ELIMINAR).setCellRenderer(new GestionCeldas("icono")); 
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem crearCliente;
    private javax.swing.JMenuItem crearCoche;
    private javax.swing.JMenuItem crearConsionario;
    private javax.swing.JMenuItem crearFabricante;
    private javax.swing.JMenuItem crearVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tVentas;
    // End of variables declaration//GEN-END:variables

    
    
     private int idTabla(int fila) {
        String id = (String) modelo.getValueAt(fila, 0);
        int Id = Integer.parseInt(id);
        return Id;
    }

 
    private  JDialog emergenteA(int fila, String titulo){
            if(fila >0){
                  int id = idTabla(fila); 
            }
           JDialog frame = new JDialog(this,titulo, true);
           frame.setLocation(this.getX(), this.getY());
           return frame;
    }
    private void emergeteB(JDialog frame){
            frame.pack();
            frame.setVisible(true);
            construirTabla();
            restaurarEscucha();
    } 
     
     
    @Override
    public void mouseClicked(MouseEvent e) {
        int fila = tVentas.rowAtPoint(e.getPoint());
        int columna = tVentas.columnAtPoint(e.getPoint());
        int id = idTabla(fila);
        switch (columna) {
            case Utilidades.COCHE:
                {
                    JDialog a = emergenteA(fila, "Editar coche");
                    a.add(new FormularioCoche(id));
                    emergeteB(a);
                    break;
                }
            case Utilidades.CONCESIONARIO:
                {
                    JDialog a = emergenteA(fila, "Editar Concesionario");
                    a.add(new FormularioConcesionario(id));
                    emergeteB(a);
                    break;
                }
            case Utilidades.CLIENTE:
                {
                    JDialog a = emergenteA(fila, "Editar Cliente");
                    a.add(new FormularioCliente(id));
                    emergeteB(a);
                    break;
                }
            case Utilidades.ELIMINAR:
                  Controlador.eliminarVenta(id);
                  construirTabla();
                break;
             default:
                break;
        }
        
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
      
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
       
    }

    @Override
    public void mouseEntered(MouseEvent e) {
       
    }

    @Override
    public void mouseExited(MouseEvent e) {
       
    }
    
     private void actualizaCelda(TableModelEvent e) {
        String id = (String) modelo.getValueAt(e.getFirstRow(), 0);
        System.out.println(modelo.getValueAt(e.getFirstRow(), 0));
        int Id = Integer.parseInt(id);
        String cambio = (String) modelo.getValueAt(e.getFirstRow(), e.getColumn());
        Controlador.actualizarMo(Id, (Integer.valueOf(e.getColumn())), cambio);
    }

     private void errorTextoDialog(String mensaje) {
        JOptionPane.showMessageDialog(this,
                mensaje,
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
     
     
    @Override
    public void tableChanged(TableModelEvent e) {        
        String Cambio = (String) modelo.getValueAt(e.getFirstRow(), e.getColumn());
        if (e.getColumn() == Utilidades.FECHA) {
           if (true) {
                actualizaCelda(e);
            } else {
                errorTextoDialog("error en datos");
                construirTabla();
                restaurarEscucha();
            }
        }else if(e.getColumn() == Utilidades.PRECIO){
             actualizaCelda(e);
        }
        
        
        
        
        
        
        
        
        
        
    }
}
